baseURL = "https://brennanbrown.ca/"
languageCode = "en-us"
theme = "portio"
title = "Writing, Marketing & Tech"

[pagination]
pagerSize = 6
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Berry House"
url = "#berryhouse"
weight = 2
[[menu.main]]
name = "About"
url = "#about"
weight = 3
[[menu.main]]
name = "Books"
url = "books"
weight = 4
[[menu.main]]
name = "Work"
url = "portfolio"
weight = 5
[[menu.main]]
name = "Writing"
url = "blog"
weight = 6
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 7
[[menu.main]]
name = "Support Me"
url = "tiers"
weight = 8
[[menu.main]]
name = "Contact"
url = "contact"
weight = 9

# Sitemap Menu
[[menu.sitemap]]
name = "Homepage"
url = "https://brennanbrown.ca"
weight = 1
[[menu.sitemap]]
name = "Resume/CV"
url = "Resume.pdf"
weight = 2
[[menu.sitemap]]
name = "Source Code"
url = "https://github.com/brennanbrown/marketing"
weight = 3
[[menu.sitemap]]
name = "Contact"
url = "contact"
weight = 4


[params]
blogPageURL = "writing"
contactLink = "contact"
copyright = "All Rights Reserved. Copyright Â© Brennan Kenneth Brown 2020 -- 2025"
footerLogo = "images/contact/footer-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/2ORFL1T"
googleAnalytics = "G-GRLVE97S23"
logo = "images/site-navigation/logo.png"
custom_css = ["css/custom.css"]

[markup.goldmark.renderer]
unsafe = true

[params.address]
address = "Calgary, Alberta, Canada"
email = "mail@brennanbrown.ca"
openingHours = "Available anytime."


[params.map]
APIkey = "AIzaSyD2WardCPFCJsUgTeWNlMDEWJe5lL-YCfM"
latitude = "51.047310"
longitude = "-114.057970"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-github-alt"
url = "https://www.github.com/brennanbrown"
weight = 1
[[params.social]]
icon = "fa-linkedin"
url = "https://www.linkedin.com/in/brennankbrown"
weight = 2
[[params.social]]
icon = "fa-tumblr"
url = "https://bkpoetry.com/"
weight = 3
[[params.social]]
icon = "fa-medium"
url = "https://blog.brennanbrown.ca"
weight = 4
[[params.social]]
icon = "fa-cloud"
url = "https://bsky.app/profile/brennan.bsky.social"
weight = 5
[[params.social]]
icon = "fa-mastodon"
url = "https://mastodon.social/@brennan"
weight = 6
[[params.social]]
icon = "fa-graduation-cap"
url = "https://www.researchgate.net/profile/Brennan-Brown-2"
weight = 7
[[params.social]]
icon = "fa-envelope"
url = "mailto:mail@brennanbrown.ca"
weight = 8
